services:
  - type: web
    name: portfolio
    env: python
    buildCommand: bash core/build.sh
    startCommand: gunicorn --chdir core core.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.2